services:
  frontend:
    build:
      context: .
      dockerfile: cahfrontend/Dockerfile
    ports:
      - "8001:80"
    networks: 
      - cah
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8002:8080"
    networks: 
      - cah
  gateway:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    ports:
      - "8000:80"
    networks:
      - cah

networks:
  cah:
    driver: bridge
