services:
  frontend:
    build:
      context: .
      dockerfile: cahfrontend/Dockerfile
    ports:
      - "8001:80"
    networks: 
      - cah
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8002:8080"
    networks: 
      - cah
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/res/packs"]
      interval: 30s
      timeout: 10s
      retries: 3
  gateway:
    build:
      context: devProxy
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - cah
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  cah:
    driver: bridge
