name: Coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: yes
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: npm i -g pnpm
      - name: Git submodules (no clue why checkout has not got them)
        run: |
          git submodule init
          git submodule update
      - name: Build the package
        run: make -j
      - name: Test the package and, generate coverage reports (backend)
        run: |
          cd backend
          go test -v -benchmem -parallel 16 ./... -covermode=atomic -coverprofile=coverage.out
      - name: Test the package and, generate coverage reports (frontend)
        run: |
          npm i -g @vitest/coverage-v8
          cd cahfrontend 
          npx vitest run --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: yes
          files: ./backend/coverage.out,./cahfrontend/coverage-final.json
          token: ${{ secrets.CODECOVIO }}
          verbose: yes
