name: e2e

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: yes
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 21
      - run: npm i -g pnpm
      - name: Git submodules (no clue why checkout has not got them)
        run: |
          git submodule init
          git submodule update
      - name: Build the package
        run: make -j
      - name: Run the end-to-end tests
        run: |
          make test -j
